---
apiVersion: datalineup.khulnasoft.io/v1alpha1
kind: DatalineupTopic
metadata:
  name: backpressure-stdout
spec:
  type: FileTopic
  options:
    path: "-"
    mode: "w"
---
apiVersion: datalineup.khulnasoft.io/v1alpha1
kind: DatalineupTopic
metadata:
  name: backpressure-input
spec:
  type: StaticTopic
  options:
    messages:
    - args: {}
    cycle: true
---
apiVersion: datalineup.khulnasoft.io/v1alpha1
kind: DatalineupTopic
metadata:
  name: backpressure-bounded-queue
spec:
  type: RabbitMQTopic
  options:
    queue_name: backpressure-bounded-queue
    max_length: 10
    prefetch_count: 5
---
apiVersion: datalineup.khulnasoft.io/v1alpha1
kind: DatalineupJobDefinition
metadata:
  name: backpressure-fast-pipeline
  labels:
    owner: team-datalineup
spec:
  minimalInterval: "@weekly"
  template:
    input:
      topic: backpressure-input

    output:
      default:
        - topic: backpressure-bounded-queue

    pipeline:
      name: example.pipelines.fast
---
apiVersion: datalineup.khulnasoft.io/v1alpha1
kind: DatalineupJobDefinition
metadata:
  name: backpressure-slow-pipeline
  labels:
    owner: team-datalineup
spec:
  minimalInterval: "@weekly"
  template:
    input:
      topic: backpressure-bounded-queue

    output:
      default:
        - topic: backpressure-stdout

    pipeline:
      name: example.pipelines.slow
      resources: {"api_key": "example.resources.BackpressureApiKey"}
---
apiVersion: datalineup.khulnasoft.io/v1alpha1
kind: DatalineupResource
metadata:
  name: backpressure-resource
spec:
  type: example.resources.BackpressureApiKey
  data: {}
  default_delay: 10
