apiVersion: datalineup.khulnasoft.io/v1alpha1
kind: DatalineupInventory
metadata:
  name: join-and-loop-inventory
spec:
  type: datalineup_engine.worker.inventories.joined.JoinInventory
  options:
    root:
      type: datalineup_engine.worker.inventories.static.StaticInventory
      name: static
      options:
        items:
          - {x: 1}
          - {x: 2}
          - {x: 3}
    join:
      type: datalineup_engine.worker.inventories.loop.LoopInventory
      name: loop
---
apiVersion: datalineup.khulnasoft.io/v1alpha1
kind: DatalineupJobDefinition
metadata:
  name: join-and-loop-inventory
  labels:
    owner: team-datalineup
spec:
  minimalInterval: "@weekly"
  template:
    input:
      inventory: join-and-loop-inventory
    output:
      default:
        - topic: stdout
    pipeline:
      name: example.pipelines.join_and_loop
---
